baseURL = 'https://blog.shinetechsoftware.org/'
languageCode = 'en-us'
defaultContentLanguage = "en"
title = 'Blog'
theme = "cayman"

# Google analytics
# googleAnalytics = "UA-123456789-1"

# Disqus comments
disqusShortname = "shinetech-software-blog"

# Syntax highlighting
pygmentsCodefences = true
pygmentsStyle = "pygments"

[taxonomies]
  tag = "tags"

[permalinks]
  post = "/:year/:month/:filename/"

[params]
  project_name = "Shinetech Software"
  project_tagline = "Open Community Team Blog"
  dateFormat = "2006-01-02"

  # Footer text, can be markdown
  footer = "* [GitHub](https://github.com/shinetechopen)\n * [Shinetech Software](https://www.shinetechsoftware.com/)"

  # If true, the CSS/JS for Katex math typesetting are enabled
  katex = true

  # Breakpoints
  large_breakpoint = "64em"
  medium_breakpoint = "42em"

  # Header colors
  header_heading_color = "#fff"
  header_background_color = "#159957"
  header_background_color_secondary = "#155799"

  # Text colors
  section_headings_color = "#159957"
  body_text_color = "#606c71"
  body_link_color = "#1e6bb8"
  blockquote_text_color = "#819198"

  # Code colors
  code_background_color = "#f3f6fa"
  code_text_color = "#567482"

  # Border colors
  border_color = "#dce6f0"
  table_border_color = "#e9ebec"
  hr_border_color = "#eff0f1"

[menu]
  [[menu.nav]]
    name = "Blog"
    url = "/"
    weight = 1
  [[menu.nav]]
    name = "Tags"
    url = "/tags/"
    weight = 2
  [[menu.nav]]
    name = "GitHub"
    url = "https://github.com/shinetechopen"
    weight = 3
  [[menu.nav]]
    name = "RSS"
    url = "/index.xml"
    weight = 4
